// <auto-generated />
namespace Comprei.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatehousestorageaddeddates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatehousestorageaddeddates));
        
        string IMigrationMetadata.Id
        {
            get { return "202306051515432_update-house-storage-added-dates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
